# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
parameters:
  - name: BuildAgent
    displayName: Build Agent
    
jobs:
- job: PowerShellExamplesUpdate
  pool: $(BuildAgent)
  timeoutInMinutes: 1200
  steps:
  
  - task: PowerShell@2
    displayName: 'Update Examples From Graph Reference'
    continueOnError: false
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: $(System.DefaultWorkingDirectory)/tools/ExamplesGenerator.ps1

  - task: PowerShell@2
    displayName: Pushing updated examples to github
    env:
      GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    inputs:
      targetType: inline
      script: |
        $date = Get-Date -Format "dd-MM-yyyy"
        $proposedBranch = "WeeklyOpenApiDocsDownload/Examples_Update_"+$date
        git status
        git add .
        git commit -m "Updating examples "+$date
        git push --set-upstream "https://${env:GITHUB_TOKEN}@github.com/microsoftgraph/msgraph-sdk-powershell.git" $proposedBranch
        git status
         